title: 像素信标
description: 像素信标 (Pixel Beacon) - 你的数字生活导航。我们致力于在浩瀚的互联网中，为你搜寻那些值得关注的效率工具、实用软件、精品资源与优质教程。
theme: minima

url: "https://x-wuxl.github.io"
# 网站的子路径，必须与仓库名完全一致
baseurl: ""


# 增加下面这个 plugins 列表
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Analytics ID
google_analytics: G-G21L5FTFZH

# 文章URL格式配置，避免中文分类导致的URL编码问题
permalink: /:year/:month/:day/:title/

# 排除不需要发布到网站上的文件或文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - PROJECT_CONTEXT.md
  - 文章 Front Matter 优化模板.md
  - category/tutorials.md
  - category/money-making.md
  - category/tech-tutorials.md
  - category/software-tools.md
  - category/shopping-guide.md